### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'set_exp_name'

### ISSUE THREAD

**Issue by zhangzk123** [smearle/pathfinding-nca#1]
When running main.py, an error is reported： 'Config' object has no attribute 'set_exp_name'.There is no method set in the Config class_ exp_ name

**Comment by smearle** [comment]
Currently, due to integration with hydra, the code must be run with `python run_batch.py`. The first time you run this, set `gen_new_data=True` to generate a new dataset of mazes for the first time. Use `+sweep=cut_corners` (for example), to select which of the hyperparameter sweeps detailed in configs/sweeps you would like to run. I believe the default sweep, `all` should launch just one experiment using an NCA with relatively "vanilla" hyperparameters.

Apologies for this! The Readme should be updated to reflect this until we can debug running "main.py" directly (though perhaps this is not really necessary).

**Comment by smearle** [comment]
I've updated the Readme to remove instructions about running `main.py` directly in cba75e110118064d41850161c1efad650e05d8e5. Let me know if the issue persists.

**Comment by zhangzk123** [comment]
Thank you for your prompt reply.The problem has been solved.This is the first time I have asked questions on github.It is really a good experience




---- Replied Message ----
| From | Sam ***@***.***> |
| Date | 10/25/2022 00:56 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [smearle/pathfinding-nca] AttributeError: 'Config' object has no attribute 'set_exp_name' (Issue #1) |

Currently, due to integration with hydra, the code must be run with python run_batch.py. The first time you run this, set gen_new_data=True to generate a new dataset of mazes for the first time. Use +sweep=cut_corners (for example), to select which of the hyperparameter sweeps detailed in configs/sweeps you would like to run. I believe the default sweep, all should launch just one experiment using an NCA with relatively "vanilla" hyperparameters.

Apologies for this! The Readme should be updated to reflect this until we can debug running "main.py" directly (though perhaps this is not really necessary).

**Comment by smearle** [comment]
No problem! This is research code, and probably a bit confusing to find your way around at first. But I'm more than happy to help you get set up and improve the code wherever possible :) Thanks for your interest!
